# Production Override - Optimized for performance and scaling

services:
  whisper-core:
    environment:
      - WHISPER_DEFAULT_MODEL=base
      - LOG_LEVEL=INFO
    restart: always
    # Remove container_name for production to allow scaling

  # Production API Gateway
  whisper-api:
    image: nginx:alpine
    # container_name: whisper-api-gateway  # Removed for multi-stack compatibility
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - whisper-network
    depends_on:
      - whisper-core
    restart: always
    profiles:
      - api

  # Production Web UI
  whisper-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    # container_name: whisper-ui-prod  # Removed for multi-stack compatibility
    environment:
      - NODE_ENV=production
    networks:
      - whisper-network
    restart: always
    profiles:
      - ui

  # Enable queue processing by default in production
  redis:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: always

  whisper-worker:
    deploy:
      replicas: 4
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1.5G
    restart: always